name: CKAN Docker Daily Image CI

on:
  workflow_dispatch:
  push:
   branches: [ cioos ]
  pull_request:
    branches: [ cioos ]

jobs:
  build:
    name: build ckan docker image 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git checkout cioos
    - run: git submodule init
    - run: git submodule update 
    - run: cp ./contrib/docker/.env.template ./contrib/docker/.env
    - run: cp ./contrib/docker/production_root_url.ini ./contrib/docker/production.ini
    - run: cp ./contrib/docker/who_root_url.ini ./contrib/docker/who.ini
    - run: cp ./contrib/docker/pycsw/pycsw.cfg.template ./contrib/docker/pycsw/pycsw.cfg
    - name: Set current date as TAG env variable for push requests
      if: github.event_name != 'pull_request'
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV    
    - name: Set PR number as TAG env variable for push requests
      if: github.event_name == 'pull_request'
      run: echo "TAG=PR${{ github.event.pull_request.number }}" >> $GITHUB_ENV    
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: docker build -t cioos/ckan:$TAG -t cioos/ckan:latest .
    - run: docker push cioos/ckan:$TAG
    - run: docker push cioos/ckan:latest

