name: CKAN Docker Daily Image CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ cioos ]
  #pull_request:
  #  branches: [ cioos ]
  #schedule:
  #  - cron: '1 1 * * *'

jobs:

  build:
    name: build ckan docker image 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Init Project
      run: |  
        git checkout cioos
        git submodule init
        git submodule update 
        cd ./contrib/docker/
        cp .env.template .env
        cp production_root_url.ini production.ini
        cp who_root_url.ini who.ini
        cp ./pycsw/pycsw.cfg.template ./pycsw/pycsw.cfg
        cd ../../
      shell: bash  
    - name: Set current date as TAG env variable
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cioos-ckan-daily:$TAG
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: cioos/ckan
        #tag_with_ref: true

