name: CKAN Docker Daily Image CI

on:
  workflow_dispatch:
  #push:
  #  branches: [ cioos ]
  #pull_request:
  #  branches: [ cioos ]
  #schedule:
  #  - cron: '1 1 * * *'

jobs:

  build:
    name: build ckan docker image 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1      
#     - name: Init Project
#       run: |  
#         git checkout cioos
#         git submodule init
#         git submodule update 
#         cd ./contrib/docker/
#         cp .env.template .env
#         cp production_root_url.ini production.ini
#         cp who_root_url.ini who.ini
#         cp ./pycsw/pycsw.cfg.template ./pycsw/pycsw.cfg
#         cd ../../
#       shell: bash 
    - run: git checkout cioos
    - run: git submodule init
    - run: git submodule update 
    - run: cp ./contrib/docker/.env.template ./contrib/docker/.env
    - run: cp ./contrib/docker/production_root_url.ini ./contrib/docker/production.ini
    - run: cp ./contrib/docker/who_root_url.ini ./contrib/docker/who.ini
    - run: cp ./contrib/docker/pycsw/pycsw.cfg.template ./contrib/docker/pycsw/pycsw.cfg
    - name: Set current date as TAG env variable
      run: echo "TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV      
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag cioos-ckan-daily:$TAG
#     - name: Push to Docker Hub
#       uses: docker/build-push-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
#         repository: cioos/ckan
#         #tag_with_ref: true
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: | 
          cioos/ckan:latest
          cioos/ckan:${{env.TAG}}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
